
export const SESSION_NEW = 'SESSION_NEW';
export const SESSION_INIT = 'SESSION_INIT';
export const SESSION_NEXT_INTERVENTION = 'SESSION_NEXT_INTERVENTION';
export const SESSION_RESET = 'SESSION_RESET';
export const SESSION_NEXT_SECTION = 'SESSION_NEXT_SECTION';
export const SESSION_RESET_SECTION = 'SESSION_RESET_SECTION';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_FETCHING = 'USER_LOGIN_FETCHING';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER_POSTING = 'USER_REGISTER_POSTING';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

export const RESULTS_SENDING = 'RESULTS_SENDING';
export const RESULTS_SEND_SUCCESS = 'RESULTS_SEND_SUCCESS';
export const RESULTS_SEND_FAILURE = 'RESULTS_SEND_FAILURE';
export const RESULTS_FETCHING = 'RESULTS_FETCHING';
export const RESULTS_FETCH_SUCCESS = 'RESULTS_FETCH_SUCCESS';
export const RESULTS_FETCH_FAILURE = 'RESULTS_FETCH_FAILURE';

export const RESULTS_PUSH_SECTION = 'RESULTS_PUSH_SECTION';
export const RESULTS_PUSH_KEYSTROKES = 'RESULTS_PUSH_KEYSTROKES';
export const RESULTS_PUSH_DISTRACTIONS= 'RESULTS_PUSH_DISTRACTIONS';
